authentication/urls.py
from django.urls import path
from .import views


urlpatterns = [
        path('register', views.register, name='register'),
        path('login', views.login, name='login'),
        path('logout', views.logout, name='logout'),
]

home/urls.py
from django.urls import path
# from .import views

from .views import(
    QuizListView,
    quiz,
    quiz_data_view,
    save_quiz_view
)

urlpatterns = [
    path('', QuizListView.as_view(), name = 'home'),
    path('<pk>/', quiz, name = 'quiz'),
    path('<pk>/data/', quiz_data_view, name = 'quiz_data_view'),
    path('<pk>/save/', save_quiz_view, name = 'save_quiz_view'),
    
]

questions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
]

quiz_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('questions/', include('questions.urls')),
    path('results/', include('results.urls')),
    path('authentication/', include('authentication.urls')),

]

results/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
]

authentication/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models
import random
# Create your models here.

DIFF_CHOICES = (
    ('Easy', 'Easy'),
    ('Medium', 'Medium'),
    ('Hard', 'Hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    pass_mark = models.IntegerField(help_text="required score in %")
    difficulty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    class Meta:
        verbose_name_plural = 'Quizes'

    def __str__(self):
        return f"{self.name} {self.topic}"
    

    def get_questions(self):
        # this random function is to pick random questions to the users display
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]
        # return self.question_set.all()[:self.number_of_questions]

questions/models.py
from django.db import models
from home.models import Quiz

# Create your models here.


class Question(models.Model):
    text = models.CharField(max_length = 200)
    quiz = models.ForeignKey(Quiz, on_delete= models.CASCADE) 
    created = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answer_set.all()


class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return f"Question: {self.question.text}, Answer: {self.text}, correct:{self.correct}"

results/models.py
from django.db import models
from home.models import Quiz
from django.contrib.auth.models import User
# Create your models here.

class Results(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    class Meta:
        verbose_name_plural = 'Results'

    def __str__(self):
        return str(self.pk)
    
    

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout  
from django.contrib import messages

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'authentication/register.html', {'form': form})

def login(request): 
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user) 
            messages.success(request, f'Welcome back, {user.username}!')
            return redirect('home')
        else:
            messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    return render(request, 'authentication/login.html', {'form': form})

def logout(request): 
    auth_logout(request)  
    messages.success(request, 'You have been logged out successfully.')
    return redirect('login')

home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import *
from django.http import JsonResponse
from questions.models import *
from results.models import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.


# if i want users to start immediately from the login page
# @method_decorator(login_required(login_url='login'), name='dispatch')
class QuizListView(ListView):
    model = Quiz
    template_name = 'home/home.html'

@login_required(login_url='authentication/login')
def quiz(request, pk):
    quiz = Quiz.objects.get(pk = pk)

    context = {
        'quiz' : quiz,
    }
    return render(request, 'home/quiz.html', context)

@login_required(login_url='authentication/login')
def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk =pk)
    questions = []
    for question in quiz.get_questions():
        answers = []
        for ans in question.get_answers():
            answers.append(ans.text)
        questions.append({str(question): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })

@login_required(login_url='authentication/login')
def save_quiz_view(request, pk):
    # print(request.POST)
    # if request.is_ajax(): # this does not work in django 5.0 and was depreciated in 4.0
    if request.headers.get('X-Requested-With') == "XMLHttpRequest": # this is what works with django 5.0
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        # print(type(data))
        # print(type(data_))
        # print(data_)
        data_.pop('csrfmiddlewaretoken')
        # print(data_)

        for k in data_.keys():
            print('Question: ', k)
            question = Question.objects.get(text = k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk = pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None


        for q in questions:
            a_selected = request.POST.get(str(q.text))
            
            if a_selected != '':
                question_answers = Answer.objects.filter(question = q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                        else:
                            if a.correct:
                                correct_answer = a.text

                results.append({str(q): {'correct_answer' : correct_answer, 'answered' : a_selected}})
            else:
                results.append({str(q): 'not answered'})


        score_ = score * multiplier
        Results.objects.create(quiz = quiz, user =user, score = score_)
        
        if score_ >= quiz.pass_mark:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed' : False, 'score': score_, 'results': results})

questions/views.py
from django.shortcuts import render

# Create your views here.

results/views.py
from django.shortcuts import render

# Create your views here.

templates/authentication/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
    <p class="mt-3">Don't have an account? <a href="{% url 'register' %}">Register here</a>.</p>
</div>
{% endblock content %}

templates/authentication/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <p class="mt-3">Already have an account? <a href="{% url 'login' %}">Login here</a>.</p>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta Developer="Olaneye Ahmed Oladapo">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quiz App</title>
    <link rel="icon" type="image/x-icon" href="{% static 'image/quiz.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/home.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Quiz App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
<div class="modal fade" id="StartQuiz" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Test</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body-confirm"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                <button type="button" id="start-button" class="btn btn-success">Yes</button>
            </div>
        </div>
    </div>
</div>

{% if user.is_authenticated %}
    <div class="alert alert-success" role="alert">
        Welcome, <strong>{{ user.username }}</strong>! Ready to take a quiz?
    </div>
{% else %}
    <div class="alert alert-warning" role="alert">
        Please <a href="{% url 'login' %}" class="alert-link">Login</a> or <a href="{% url 'register' %}" class="alert-link">Register</a> to take a quiz.
    </div>
{% endif %}

<div class="h1">Quiz List</div>
<hr>
{% if user.is_authenticated %}
    <div class="row">
        {% for quiz in quiz_list %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ quiz.name }}</h5>
                    <p class="card-text">
                        <span class="badge badge-primary">{{ quiz.difficulty }}</span>
                        <span class="badge badge-secondary">{{ quiz.number_of_questions }} Questions</span>
                        <span class="badge badge-info">{{ quiz.time }} mins</span>
                        <span class="badge badge-success">{{ quiz.pass_mark }}% Pass Mark</span>
                    </p>
                </div>
                <div class="card-footer bg-transparent">
                    <button
                        class="btn btn-primary btn-block modal-button"
                        data-pk="{{ quiz.pk }}"
                        data-quiz="{{ quiz.name }}"
                        data-questions="{{ quiz.number_of_questions }}"
                        data-difficulty="{{ quiz.difficulty }}"
                        data-time="{{ quiz.time }}"
                        data-pass_mark="{{ quiz.pass_mark }}"
                        data-toggle="modal"
                        data-target="#StartQuiz">
                        Start Quiz
                    </button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% else %}
    <div class="alert alert-info" role="alert">
        You must be logged in to view the quiz list.
    </div>
{% endif %}

<script src="{% static 'js/home.js' %}" defer></script>
{% endblock content %}

templates/home/quiz.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ quiz.name }}
{% endblock title %}

{% block content %}
<div class="container py-4">
    <div class="row align-items-center mb-4">
        <div class="col-md-8">
            <h1 class="display-4">{{ quiz.name }}</h1>
            <p class="lead">Pass Mark: <strong>{{ quiz.pass_mark }}%</strong></p>
        </div>
        <div class="col-md-4 text-right">
            <div id="timer-box" class="badge badge-primary p-3 h4"></div>
        </div>
    </div>

    <form id="quiz-form">
        {% csrf_token %}
        <div id="quiz-box" class="bg-light p-4 rounded shadow-sm mb-4">
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-lg btn-success px-5">Submit</button>
        </div>
    </form>

    <div id="score-box" class="mt-4 text-center h4"></div>
    <div id="result-box" class="mt-4"></div>
</div>

<script src="{% static 'js/quiz.js' %}" defer></script>
{% endblock content %}